CardDict = {
    "Card Of Steel": "Swords are all +X",
    "Card Of Growth": "All Standard Potions +X",
    "Card Of Life": "Max Health +X",
    "Card Of Drink": "Add an extra (X) potion to each floor",
    "Card Of Swords": "Double one random Basic Sword per floor",
    "Card Of Wealth": "All Chests are +X",
    "Card Of Heroes": "Full heal if you clear the whole floor",
    "Card Of Wood": "Take X Less damage from thorns",
    "Card Of Eyes": "All stacks visible at the start of each level",
    "Card Of Bones": "No Hoarders",
    "Card Of Knowledge": "Start with one random Scroll",
    "Card Of Privilege": "Each floor starts with a treasure in the first row",
    "Card Of Iron": "Daggers are all +X",
    "Card Of Luck": "X% chance that Potions will heal you double",
    "Card Of Equals": "Basic Swords are all X",
    "Card Of Strength": "Potion of Strength increases my bare-handed attack by X",
    "Card Of Return": "first time you are killed in a dungeon, revive with X hp",
    "Card Of Aggression": "first weapon you pick up on each floor is doubled",
    "Card Of Cruelty": "Picking up a Potion does X damage to adjacent cards",
    "Card Of Chaos": "Gain one HP each turn you're confused",
    "Card Of Clarity": "X% chance a card will show through confusion",
    "Card Of Study": "50% fewer scrolls, but 50% of the time when you cast a spell, the scroll is not used up",
    "Card Of Truth": "Fart every time",
    "Card Of Plagues": "All poison does X damage a turn",
    "Card Of Stalwarts": "You cannot die from poison",
}
